### ISSUE TITLE
Rerun for Coordinator Action Failing when there are no "output-events" defined

### ISSUE THREAD

**Issue by mikelikespie** [YahooArchive/oozie#210]
Getting this when trying to rerun a coordinator action:

```
2010-11-12 18:47:35,997  WARN V1JobServlet:528 - USER[?] GROUP[users] TOKEN[] APP[event_log_jobs] JOB[0000092-101108201110698-oozie-tomc-C] ACTION[-] URL[PUT http://olap01.local:8080/oozie/v1/job/0000092-101108201110698-oozie-tomc-C?scope=2&nocleanup=false&action=coord-rerun&type=action&refresh=true] error[E1018], E1018: Coord Job Rerun Error: java.lang.NullPointerException
org.apache.oozie.servlet.XServletException: E1018: Coord Job Rerun Error: java.lang.NullPointerException
        at org.apache.oozie.servlet.V1JobServlet.reRunCoordinatorActions(V1JobServlet.java:448)
        at org.apache.oozie.servlet.V1JobServlet.reRunJob(V1JobServlet.java:169)
        at org.apache.oozie.servlet.BaseJobServlet.doPut(BaseJobServlet.java:112)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:640)
        at org.apache.oozie.servlet.JsonRestServlet.service(JsonRestServlet.java:281)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
        at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:857)
        at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:588)
        at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
        at java.lang.Thread.run(Thread.java:619)
Caused by: org.apache.oozie.BaseEngineException: E1018: Coord Job Rerun Error: java.lang.NullPointerException
        at org.apache.oozie.CoordinatorEngine.reRun(CoordinatorEngine.java:199)
        at org.apache.oozie.servlet.V1JobServlet.reRunCoordinatorActions(V1JobServlet.java:442)
        ... 17 more
Caused by: org.apache.oozie.command.CommandException: E1018: Coord Job Rerun Error: java.lang.NullPointerException
        at org.apache.oozie.command.coord.CoordRerunCommand.call(CoordRerunCommand.java:126)
        at org.apache.oozie.command.coord.CoordRerunCommand.execute(CoordRerunCommand.java:379)
        at org.apache.oozie.command.coord.CoordRerunCommand.execute(CoordRerunCommand.java:51)
        at org.apache.oozie.command.Command.call(Command.java:202)
        at org.apache.oozie.CoordinatorEngine.reRun(CoordinatorEngine.java:196)
        ... 18 more
Caused by: java.lang.NullPointerException
        at org.apache.oozie.command.coord.CoordRerunCommand.cleanupOutputEvents(CoordRerunCommand.java:285)
        at org.apache.oozie.command.coord.CoordRerunCommand.call(CoordRerunCommand.java:94)
        ... 22 more
```

The culprit is in CoordRerunCommand.java here:

It doesn't check outputList for null.  Fix: add an if statement.

```
    Element outputList = eAction.getChild("output-events", eAction.getNamespace());
    for (Element data : (List<Element>) outputList.getChildren("data-out", eAction.getNamespace())) {
```

**Comment by mislam77-zz** [comment]
This was fixed. Related issue  #40.
https://github.com/yahoo/oozie/issues/issue/040

**Comment by mislam77-zz** [comment]
If you think that resolved the problem, please close this issue.
Anyway it is good find!!
