### ISSUE TITLE
JPAService is not working on derby

### ISSUE THREAD

**Issue by angeloh** [YahooArchive/oozie#418]
JPAService is not working on derby

**Comment by angeloh** [comment]
Error message of test case when running on Derby:

---

Running org.apache.oozie.client.TestWorkflowXClient

org.apache.maven.surefire.booter.SurefireExecutionException: org.apache.oozie.client.TestWorkflowXClient; nested exception is java.lang.NoClassDefFoundError: org/apache/oozie/servlet/V1JobsServlet; nested exception is org.apache.maven.surefire.testset.TestSetFailedException: org.apache.oozie.client.TestWorkflowXClient; nested exception is java.lang.NoClassDefFoundError: org/apache/oozie/servlet/V1JobsServlet
org.apache.maven.surefire.testset.TestSetFailedException: org.apache.oozie.client.TestWorkflowXClient; nested exception is java.lang.NoClassDefFoundError: org/apache/oozie/servlet/V1JobsServlet
java.lang.NoClassDefFoundError: org/apache/oozie/servlet/V1JobsServlet
        at org.apache.oozie.client.TestWorkflowXClient.<clinit>(TestWorkflowXClient.java:32)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
        at junit.framework.TestSuite.createTest(TestSuite.java:131)
        at junit.framework.TestSuite.addTestMethod(TestSuite.java:114)
        at junit.framework.TestSuite.<init>(TestSuite.java:75)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
        at org.apache.maven.surefire.junit.JUnitTestSet.constructTestObject(JUnitTestSet.java:151)
        at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:197)
        at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:120)
        at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:103)
        at org.apache.maven.surefire.Surefire.run(Surefire.java:169)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:350)
        at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1021)
Caused by: java.lang.ClassNotFoundException: org.apache.oozie.servlet.V1JobsServlet
        at java.net.URLClassLoader$1.run(URLClassLoader.java:199)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:307)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:248)
        ... 23 more
Caused by: java.io.FileNotFoundException: /homes/angeloh/workspaces/git-y-oozie-0204/oozie/core/target/classes/org/apache/oozie/servlet/V1JobsServlet.class (Too many open files)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:106)
        at sun.misc.URLClassPath$FileLoader$1.getInputStream(URLClassPath.java:1005)
        at sun.misc.Resource.cachedInputStream(Resource.java:61)
        at sun.misc.Resource.getByteBuffer(Resource.java:144)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:256)
        at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
        ... 28 more

---

**Comment by tucu00** [comment]
Angelo,

It seems you have too many open files. 
- have you tried setting your ulimit to a higher value?
- what is the Maven command line you are using to run the testcases with Derby?

**Comment by angeloh** [comment]
what do yu mean by ulimit? bin/mkdidtro.sh is used.

**Comment by angeloh** [comment]
Closed by efe653185713b91b1ff36ed48002d25a4dbaea0c Fix JPAService for Derby
