### ISSUE TITLE
bundle rerun failed with E0303

### ISSUE THREAD

**Issue by mislam77-zz** [YahooArchive/oozie#522]
Error: E0303 : E0303: Invalid parameter value, [action] = [bundle-rerun]

2011-02-18 17:57:09,159  WARN V1JobServlet:528 - USER[mchiang] GROUP[-] TOKEN[-] APP[-] JOB[-] ACTION[-] URL[PUT http://IP:4080/oozie/v1/job/0000047-110217053021536-oozie-oozi-B?date-scope=2009-10-03T01%3A00Z&nocleanup=false&action=bundle-rerun&refresh=false]
error[E0303], E0303: Invalid parameter value, [action] = [bundle-rerun]
org.apache.oozie.servlet.XServletException: E0303: Invalid parameter value, [action] = [bundle-rerun]
        at org.apache.oozie.servlet.BaseJobServlet.doPut(BaseJobServlet.java:129)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:640)
        at org.apache.oozie.servlet.JsonRestServlet.service(JsonRestServlet.java:281)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at com.yahoo.oozie.filter.OozieAuthFilter.doFilter(OozieAuthFilter.java:40)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at
org.apache.hadoop.http.authentication.web.AuthenticationProcessingFilter.doFilter(AuthenticationProcessingFilter.java:75)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at yjava.security.yiv.servlet.InputValidationFilter.doFilter(InputValidationFilter.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at yjava.tomcat.valves.YahooConnectionValve.doFilter(YahooConnectionValve.java:80)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:128)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
        at yjava.tomcat.valves.YahooConnectionValve.invoke(YahooConnectionValve.java:121)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:286)
        at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:845)
        at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:583)
        at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:447)
        at java.lang.Thread.run(Thread.java:662)

**Comment by bansalmayank** [comment]
Closed by 46c05fa08b7a127bb93dbe94e6972c90c6d01d2c Bundle rerun failed
