### ISSUE TITLE
Encountered java.lang.NoSuchMethodError error after submitting a job

### ISSUE THREAD

**Issue by brookwc** [YahooArchive/oozie#606]
After submitting a wf job, the wf action will get stuck in PREP state.

In tomcat log, we saw the following errors.

---

Exception in thread "pool-2-thread-143" java.lang.NoSuchMethodError: org.apache.hadoop.mapred.JobConf.getCredentials()Lorg/apache/hadoop/security/Credentials;
  at org.apache.oozie.action.hadoop.JavaActionExecutor.submitLauncher(JavaActionExecutor.java:541)
  at org.apache.oozie.action.hadoop.JavaActionExecutor.start(JavaActionExecutor.java:701)
  at org.apache.oozie.command.wf.ActionStartXCommand.execute(ActionStartXCommand.java:183)
  at org.apache.oozie.command.wf.ActionStartXCommand.execute(ActionStartXCommand.java:53)
  at org.apache.oozie.command.XCommand.call(XCommand.java:255)
  at org.apache.oozie.service.CallableQueueService$CompositeCallable.call(CallableQueueService.java:282)
  at org.apache.oozie.service.CallableQueueService$CompositeCallable.call(CallableQueueService.java:229)
  at org.apache.oozie.service.CallableQueueService$CallableWrapper.run(CallableQueueService.java:148)
  at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
  at java.lang.Thread.run(Thread.java:619)

---

I am using Hadoop 0.20.2 (non-secured). Looks like the code can only work with secured hadoop.

**Comment by mislam77-zz** [comment]
Closed by 9466f83973b274b6a464b0d71877d02d2767ba4e Encountered java.lang.NoSuchMethodError error after submitting a job
