### ISSUE TITLE
NoSuchMethodError with Apache 0.20.2

### ISSUE THREAD

**Issue by dwchang** [YahooArchive/oozie#710]
unable to start with Apache Hadoop 0.20.2

all default settings

Apr 11, 2011 6:41:46 PM org.apache.catalina.core.StandardContext listenerStart
SEVERE: Exception sending context initialized event to listener instance of class org.apache.oozie.servlet.ServicesLoader
Throwable occurred: java.lang.NoSuchMethodError: org/apache/hadoop/security/UserGroupInformation.setConfiguration(Lorg/apache/hadoop/conf/Configuration;)V
    at org.apache.oozie.service.KerberosHadoopAccessorService.init(KerberosHadoopAccessorService.java:92)
    at org.apache.oozie.service.HadoopAccessorService.init(HadoopAccessorService.java:72)
    at org.apache.oozie.service.Services.setServiceInternal(Services.java:307)
    at org.apache.oozie.service.Services.setService(Services.java:293)
    at org.apache.oozie.service.Services.init(Services.java:203)
    at org.apache.oozie.servlet.ServicesLoader.contextInitialized(ServicesLoader.java:37)
    at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4205)
    at org.apache.catalina.core.StandardContext.start(StandardContext.java:4704)
    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:799)
    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:779)
    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:601)
    at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:675)
    at org.apache.catalina.startup.HostConfig.deployDescriptors(HostConfig.java:601)
    at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:502)
    at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1315)
    at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:324)
    at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:142)
    at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1061)
    at org.apache.catalina.core.StandardHost.start(StandardHost.java:840)
    at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1053)
    at org.apache.catalina.core.StandardEngine.start(StandardEngine.java:463)
    at org.apache.catalina.core.StandardService.start(StandardService.java:525)
    at org.apache.catalina.core.StandardServer.start(StandardServer.java:754)
    at org.apache.catalina.startup.Catalina.start(Catalina.java:595)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:45)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)
    at java.lang.reflect.Method.invoke(Method.java:599)
    at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:289)
    at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:414)

**Comment by mislam77-zz** [comment]
Hi,
This is related to KerberoesHadoopAccessorService defined in oozie-defaults.xml 
file.

I have an unclean workaround (does anyone have better one?). Looks like it is 
becoming a repeat issue.

Work-around:
Copy the contents of  property "oozie.services" from oozie-defaults.xml (nearly 
33 lines) and add the whole property into oozie-site.xml. Then replace the word 
"KerberoesHadoopAccessorService" with "HadoopAccessorService" from the value.

Restart tomcat. It should resolve the issue.

Regards,
Mohammad

---

From: dwchang 
reply@reply.github.com
To: mislam77@yahoo.com
Sent: Mon, April 11, 2011 6:44:00 PM
Subject: [GitHub] NoSuchMethodError with Apache 0.20.2 [yahoo/oozie GH-710]

unable to start with Apache Hadoop 0.20.2

all default settings

Apr 11, 2011 6:41:46 PM org.apache.catalina.core.StandardContext listenerStart
SEVERE: Exception sending context initialized event to listener instance of 
class org.apache.oozie.servlet.ServicesLoader
Throwable occurred: java.lang.NoSuchMethodError: 
org/apache/hadoop/security/UserGroupInformation.setConfiguration(Lorg/apache/hadoop/conf/Configuration;)V

```
at 
```

org.apache.oozie.service.KerberosHadoopAccessorService.init(KerberosHadoopAccessorService.java:92)

```
at 
```

org.apache.oozie.service.HadoopAccessorService.init(HadoopAccessorService.java:72)

```
at org.apache.oozie.service.Services.setServiceInternal(Services.java:307)
at org.apache.oozie.service.Services.setService(Services.java:293)
at org.apache.oozie.service.Services.init(Services.java:203)
at 
```

org.apache.oozie.servlet.ServicesLoader.contextInitialized(ServicesLoader.java:37)

```
at 
```

org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4205)

```
at org.apache.catalina.core.StandardContext.start(StandardContext.java:4704)
at 
```

org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:799)
    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:779)
    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:601)
    at 
org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:675)
    at 
org.apache.catalina.startup.HostConfig.deployDescriptors(HostConfig.java:601)
    at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:502)
    at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1315)
    at 
org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:324)
    at 
org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:142)

```
at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1061)
at org.apache.catalina.core.StandardHost.start(StandardHost.java:840)
at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1053)
at org.apache.catalina.core.StandardEngine.start(StandardEngine.java:463)
at org.apache.catalina.core.StandardService.start(StandardService.java:525)
at org.apache.catalina.core.StandardServer.start(StandardServer.java:754)
at org.apache.catalina.startup.Catalina.start(Catalina.java:595)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at 
```

sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:45)
    at 
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)

```
at java.lang.reflect.Method.invoke(Method.java:599)
at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:289)
at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:414)
```

## 

Reply to this email directly or view it on GitHub:
https://github.com/yahoo/oozie/issues/710

**Comment by jalimay** [comment]
OK, it runs better. Thanks a lot.
