### ISSUE TITLE
oozie-stop.sh is oblivious to 'catalina.sh stop' failing

### ISSUE THREAD

**Issue by rvs** [YahooArchive/oozie#792]
Here's what happens:
# oozie-stop.sh

....
Mar 28, 2011 6:16:52 PM org.apache.catalina.startup.Catalina stopServer
SEVERE: Catalina.stop:
java.net.ConnectException: Connection refused
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:333)
        at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:195)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:182)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
        at java.net.Socket.connect(Socket.java:529)
        at java.net.Socket.connect(Socket.java:478)
        at java.net.Socket.<init>(Socket.java:375)
        at java.net.Socket.<init>(Socket.java:189)
        at org.apache.catalina.startup.Catalina.stopServer(Catalina.java:408)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.apache.catalina.startup.Bootstrap.stopServer(Bootstrap.java:338)
        at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:416)
Tomcat did not stop in time. PID file was not removed.

Oozie stopped

**Comment by rvs** [comment]
Unless there's a strong objections, I propose to add -force to the call of catalina.sh stop. Here's what it does: stop -force       Stop Catalina, wait up to 5 seconds and then use kill -KILL if still running

**Comment by tucu00** [comment]
Instead ... how about getting rid of the oozie-start/stop script and have a single oozied.sh script that propagates the arguments to the catalina script, then you could do all catalina subcommands?

**Comment by rvs** [comment]
Does this look fine? https://github.com/yahoo/oozie/pull/803
