### ISSUE TITLE
oozie 3.0.2 failing to submit jobs to hadoop 0.20.2

### ISSUE THREAD

**Issue by jabirahmed** [YahooArchive/oozie#834]
i have added these to my core-site.xml on jt an nn and restarted them

```
    <property>
            <name>hadoop.proxyuser.oozie.groups</name>
            <value>*</value>
            <description>Allow the superuser oozie to impersonate
```

any members of the group group1 and group2</description>
        </property>
        <property>
                <name>hadoop.proxyuser.oozie.hosts</name>
                <value>oozie.host1.com,oozie.host2.com</value>
                <description>The superuser can connect only from host1
and host2 to impersonate a user</description>
        </property>

in oozie-site.xml i disabled kerberos 

oozie is running as the user oozie and the sample aggregator job runs
fine when i submit it as oozie but fails when i try to submit as
anyother user

JA009: java.io.IOException: java.io.IOException: The username jabira
obtained from the conf doesn't match the username oozie the user
authenticated as  at org.apache.hadoop.mapred.JobTracker.s
ubmitJob(JobTracker.java:3759)  at
sun.reflect.GeneratedMethodAccessor21.invoke(Unknown Source) at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:
25)            at java.lang.reflect.Method.invoke(Method.java:597)
at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:557)  at
org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:1415) at
org.apache.ha    doop.ipc.Server$Handler$1.run(Server.java:1411) at
java.security.AccessController.doPrivileged(Native Method)   at
javax.security.auth.Subject.doAs(Subject.java:396)   at
org.apache.hadoop.sec
urity.UserGroupInformation.doAs(UserGroupInformation.java:1115) at
org.apache.hadoop.ipc.Server$Handler.run(Server.java:1409)Caused by:
java.io.IOException: The username jabira obtained from t    he conf
doesn't match the username oozie the user authenticated as      at
org.apache.hadoop.mapred.JobInProgress.<init>(JobInProgress.java:
423)        at org.apache.hadoop.mapred.JobTracker.s
ubmitJob(JobTracker.java:3757)  ... 10 more 

$ hadoop version
Hadoop 0.20.2-cdh3u0
Subversion  -r 81256ad0f2e4ab2bd34b04f53d25a6c23686dd14
Compiled by root on Sat Mar 26 00:12:30 UTC 2011
From source with checksum 6c1f62dddc4eac69b6b973c18bbc0f55

$ ../bin/oozie version
Oozie client build version: 3.0.2

**Comment by jabirahmed** [comment]
<property>
      <name>oozie.services.ext</name>
      <description>
            To add/replace services defined in 'oozie.services' with custom implementations.            Class names must be separated by commas.        </description>      <value>org.apache.oozie.service.HadoopAccessorService</value>
    </property>

<property>

was causing the issue
